// blogData.js
export const sampleBlogPosts = [
  {
    id: 1,
    title: "Getting Started with React: A Beginner's Guide",
    excerpt:
      "Learn how to build your first React application with this comprehensive guide for beginners.",
    author: "Alex Johnson",
    authorImage: "/api/placeholder/40/40",
    date: "Mar 5, 2025",
    readTime: 8,
    likes: 342,
    views: 5678,
    category: "React",
    image: "/api/placeholder/400/320",
    tags: ["beginner", "react", "frontend"],
  },
  {
    id: 2,
    title: "Advanced JavaScript Patterns Every Developer Should Know",
    excerpt:
      "Explore essential JavaScript patterns that will help you write cleaner and more maintainable code.",
    author: "Samantha Lee",
    authorImage: "/api/placeholder/40/40",
    date: "Mar 3, 2025",
    readTime: 12,
    likes: 520,
    views: 8790,
    category: "JavaScript",
    image: "/api/placeholder/400/320",
    tags: ["advanced", "javascript", "patterns"],
  },
  {
    id: 3,
    title: "Building a Full-Stack Application with MERN",
    excerpt:
      "Step-by-step guide on how to create a complete web application using MongoDB, Express, React, and Node.js.",
    author: "Michael Chen",
    authorImage: "/api/placeholder/40/40",
    date: "Mar 1, 2025",
    readTime: 15,
    likes: 289,
    views: 4567,
    category: "Full-Stack",
    image: "/api/placeholder/400/320",
    tags: ["mern", "full-stack", "mongodb"],
  },
  {
    id: 4,
    title: "Understanding Big O Notation for Algorithm Optimization",
    excerpt:
      "Learn how to analyze and optimize your algorithms using Big O notation and improve performance.",
    author: "David Wilson",
    authorImage: "/api/placeholder/40/40",
    date: "Feb 28, 2025",
    readTime: 10,
    likes: 456,
    views: 6789,
    category: "Algorithms",
    image: "/api/placeholder/400/320",
    tags: ["algorithms", "optimization", "computer-science"],
  },
  {
    id: 5,
    title: "CSS Grid vs. Flexbox: When to Use Each",
    excerpt:
      "Discover the strengths and weaknesses of CSS Grid and Flexbox and learn when to use each layout system.",
    author: "Emma Garcia",
    authorImage: "/api/placeholder/40/40",
    date: "Feb 25, 2025",
    readTime: 7,
    likes: 398,
    views: 5432,
    category: "CSS",
    image: "/api/placeholder/400/320",
    tags: ["css", "layout", "frontend"],
  },
  {
    id: 6,
    title: "Introduction to TypeScript for JavaScript Developers",
    excerpt:
      "A beginner-friendly guide to TypeScript and how it can enhance your JavaScript development workflow.",
    author: "Ryan Taylor",
    authorImage: "/api/placeholder/40/40",
    date: "Feb 22, 2025",
    readTime: 9,
    likes: 312,
    views: 4567,
    category: "TypeScript",
    image: "/api/placeholder/400/320",
    tags: ["typescript", "javascript", "beginner"],
  },
  {
    id: 7,
    title: "Mastering Git: Beyond the Basics",
    excerpt:
      "Take your Git skills to the next level with advanced techniques and workflows used by professional developers.",
    author: "Olivia Martin",
    authorImage: "/api/placeholder/40/40",
    date: "Feb 20, 2025",
    readTime: 11,
    likes: 278,
    views: 3890,
    category: "Git",
    image: "/api/placeholder/400/320",
    tags: ["git", "version-control", "advanced"],
  },
  {
    id: 8,
    title: "Optimizing React Performance: Tips and Tricks",
    excerpt:
      "Learn practical techniques to identify and fix performance bottlenecks in your React applications.",
    author: "James Wilson",
    authorImage: "/api/placeholder/40/40",
    date: "Feb 18, 2025",
    readTime: 13,
    likes: 489,
    views: 7654,
    category: "React",
    image: "/api/placeholder/400/320",
    tags: ["react", "performance", "optimization"],
  },
  {
    id: 9,
    title: "Creating Custom Hooks in React",
    excerpt:
      "Learn how to extract and reuse stateful logic with custom hooks to make your React components cleaner.",
    author: "Sophia Brown",
    authorImage: "/api/placeholder/40/40",
    date: "Feb 15, 2025",
    readTime: 8,
    likes: 356,
    views: 5678,
    category: "React",
    image: "/api/placeholder/400/320",
    tags: ["react", "hooks", "intermediate"],
  },
  {
    id: 10,
    title: "Building Responsive UIs with Tailwind CSS",
    excerpt:
      "A comprehensive guide to using Tailwind CSS for creating beautiful and responsive user interfaces.",
    author: "Lucas Martinez",
    authorImage: "/api/placeholder/40/40",
    date: "Feb 12, 2025",
    readTime: 9,
    likes: 423,
    views: 6789,
    category: "CSS",
    image: "/api/placeholder/400/320",
    tags: ["tailwind", "css", "responsive"],
  },
  {
    id: 11,
    title: "Experimental: The Future of Web Development",
    excerpt:
      "Exploring emerging technologies and approaches that will shape the future of web development.",
    author: "Ava Robinson",
    authorImage: "/api/placeholder/40/40",
    date: "Feb 10, 2025",
    readTime: 14,
    likes: 267,
    views: 3456,
    category: "Web Dev",
    image: "/api/placeholder/400/320",
    tags: ["future", "experimental", "trends"],
  },
  {
    id: 12,
    title: "Experimental: Machine Learning for Web Developers",
    excerpt:
      "How web developers can leverage machine learning to create more intelligent and adaptive applications.",
    author: "Noah Williams",
    authorImage: "/api/placeholder/40/40",
    date: "Feb 8, 2025",
    readTime: 12,
    likes: 345,
    views: 4567,
    category: "ML",
    image: "/api/placeholder/400/320",
    tags: ["machine-learning", "experimental", "ai"],
  },
  {
    id: 13,
    title: "Experimental: Building Micro-frontends",
    excerpt:
      "An exploration of micro-frontend architecture and how it can help teams build and deploy independent frontend modules.",
    author: "Isabella Clark",
    authorImage: "/api/placeholder/40/40",
    date: "Feb 5, 2025",
    readTime: 11,
    likes: 289,
    views: 3698,
    category: "Architecture",
    image: "/api/placeholder/400/320",
    tags: ["micro-frontends", "architecture", "experimental"],
  },
  {
    id: 14,
    title: "5 Common Data Structures Explained Simply",
    excerpt:
      "A beginner-friendly explanation of essential data structures every programmer should know.",
    author: "Ethan Thompson",
    authorImage: "/api/placeholder/40/40",
    date: "Feb 3, 2025",
    readTime: 10,
    likes: 456,
    views: 7890,
    category: "Data Structures",
    image: "/api/placeholder/400/320",
    tags: ["data-structures", "beginner", "computer-science"],
  },
  {
    id: 15,
    title: "Solving Coding Problems: A Systematic Approach",
    excerpt:
      "Learn a methodical strategy for tackling coding challenges and improving your problem-solving skills.",
    author: "Mia Johnson",
    authorImage: "/api/placeholder/40/40",
    date: "Feb 1, 2025",
    readTime: 9,
    likes: 378,
    views: 6543,
    category: "Problem Solving",
    image: "/api/placeholder/400/320",
    tags: ["problem-solving", "algorithms", "interview"],
  },
];
